### ISSUE TITLE
Move the pool down for Explore Screen

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy-basics#10]
The controls in these simulations are less big at the bottom of the screen (compared with buoyancy) that we can move the pool down, allowing more interaction with the blocks and space for the density readout in the explore screen.

**Comment by zepumph** [comment]
Noting https://github.com/phetsims/buoyancy-basics/issues/11

**Comment by AgustinVallejo** [comment]
Moved the pool down, please review and close @DianaTavares

**Comment by DianaTavares** [comment]
perfect!
