### ISSUE TITLE
Move pool to the left on both screens. 

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy-basics#11]
This is to account for the pool scale height slider.

Things to consider:

* Maxwidth of the display options node
* MaxWidth of the material sliders
* Update the compare screen number control to be the default track size.

**Comment by zepumph** [comment]
Noting https://github.com/phetsims/buoyancy-basics/issues/10

**Comment by AgustinVallejo** [comment]
Just for the record, we tried moving the camera and duh, perspective spoiled the party:

![image](https://github.com/phetsims/buoyancy-basics/assets/37052186/7c48bc3f-0503-468e-ab89-ed2ce7871c28)

Will try other solutions

**Comment by AgustinVallejo** [comment]
There's just one thing to maybe redesign here: Since the pool moved to the left, now the scale and red block on the Compare Screen don't fit and bounce against the screen bounds. Maybe thinking of a new position for the red block @DianaTavares

**Comment by DianaTavares** [comment]
It is perfect!! 

Thanks!

**Comment by zepumph** [comment]
>now the scale and red block on the Compare Screen don't fit and bounce against the screen bounds. Maybe thinking of a new position for the red block @DianaTavares

This doesn't seem complete. Let's discuss

**Comment by zepumph** [comment]
@DianaTavares, how would you like to handle the left side masses? The block positions are further to the left than the bounds allow, so resetting caused an animation ending in the block resting partially out above the pool:

<img width="789" alt="image" src="https://github.com/phetsims/buoyancy-basics/assets/6856943/f0b4fc7d-93c5-495c-afe1-7b84402664f7">


We could change the initial positions, but I can't see how to do that when without pool overlap with the large olive block on the left:

<img width="614" alt="image" src="https://github.com/phetsims/buoyancy-basics/assets/6856943/79c70cab-ef98-4353-b2e5-006936e21be8">


What do you think?

**Comment by AgustinVallejo** [comment]
@zepumph I already spoke to @DianaTavares and will fix this. We'll invert the blocks sizes. Just haven't gotten to it yet

**Comment by AgustinVallejo** [comment]
![image](https://github.com/phetsims/buoyancy-basics/assets/37052186/d3370b9c-aad7-46b3-bc3c-2781c541d646)
 
When implementing the change, the yellow block is now really close to black... Are we ok with this? @DianaTavares

**Comment by AgustinVallejo** [comment]
@DianaTavares says: está bien! 

Closing
