### ISSUE TITLE
Dev versions for interview

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy-basics#13]
Ready for interviews! that means that I need a dev version of the simulation. Thanks!! 
And also I need that dev version for the conference that I am participating this Friday.

**Comment by zepumph** [comment]
Working on it now.

**Comment by zepumph** [comment]
https://phet-dev.colorado.edu/html/buoyancy-basics/1.0.0-dev.3/phet/buoyancy-basics_all_phet.html

**Comment by DianaTavares** [comment]
It is amazing! thanks
