### ISSUE TITLE
Blocks under the scale inside the fluid, and the user drawing down the scale 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy-basics#14]
Right now it looks like this:
![image](https://github.com/phetsims/buoyancy-basics/assets/26031501/fcc560b4-4ce8-4830-9a49-8cad64f1792a)

I wonder if the slider can know where the block is and not to get down merging with the block. Other idea is to make the space below the scale inaccessible for the blocks. Other ideas?

**Comment by samreid** [comment]
In discussion with @DianaTavares and @AgustinVallejo we agreed the best solution is to prevent blocks from being dragged underneath the scale.

**Comment by samreid** [comment]
@AgustinVallejo and I worked on it in the commit. @DianaTavares can you please test this on phettest? Please close if ok.

**Comment by AgustinVallejo** [comment]
Noting that this change introduced a new bug, which is probably going to be **very hard** to solve: When you move the pool scale up very fast, small blocks on top of the scale can fall through into the wall. How much effort should we put in fixing that?



![Image](https://github.com/phetsims/buoyancy-basics/assets/37052186/c51a6c00-7332-42c5-aeee-2ad62478f56c)

**Comment by DianaTavares** [comment]
Te wall is working well!

but the bug is very distracting and easy to reproduce. 
It happens not only with small blocks, all blocks that fit below the scale can present this problem:
![image](https://github.com/phetsims/buoyancy-basics/assets/26031501/5eed2270-57e3-49c3-b266-9534b4484daa)

@AgustinVallejo indicates that it is "very hard" but approximately how much time? I will bring this to my meeting with @kathy-phet but we will need a reference to make a decision.

**Comment by AgustinVallejo** [comment]
@DianaTavares nevermind, we figured how to teleport the blocks when they found themselves trapped. Pushing a fix below

**Comment by DianaTavares** [comment]
love it!! I will close
