### ISSUE TITLE
Delete the Density Number Line from Explore Screen in B:B

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/buoyancy-basics#15]

**Comment by AgustinVallejo** [comment]
Removed the Accordion Box. @DianaTavares should this issue also include adding the other Density Readout Panel to the right? Above the submerged percentage.

**Comment by samreid** [comment]
@AgustinVallejo removed the accordion box and me, @DianaTavares and @AgustinVallejo agreed it looks good. We will work on adding that information elsewhere in another issue. Closing.
