### ISSUE TITLE
Dev version for interviews

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy-basics#16]
We made some changes in the simulation and need to test those changes with more interviews. I am calling participants to schedule interviews for next Monday (I already have one at 5 PM, but we can have another one earlier that day). Can you support me with the dev version of the most recent B:B sim?

**Comment by zepumph** [comment]
Let me know if you need anything else. 
https://phet-dev.colorado.edu/html/buoyancy-basics/1.0.0-dev.4/phet/buoyancy-basics_all_phet.html

**Comment by DianaTavares** [comment]
It is working amazing, thanks @zepumph!!
