### ISSUE TITLE
Use decimeters Cubes in Studio generate an issue with the lecture of the density 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy-basics#20]
I am testing the examples in Stidio for Buoyancy Basics and when I select Desimeter Cubes as the units for density I get this in the Blocks material's panel:

![image](https://github.com/user-attachments/assets/cb995c54-9c5f-4e05-9318-0c9ca7bc3605)

**Comment by samreid** [comment]
Fixed in both buoyancy basics: explore, and also in buoyancy lab (there was a fluid density readout with this problem). @DianaTavares can you please check through each screen of density, buoyancy, buoyancy-basics with dm^3 and see if there are others I missed?

**Comment by DianaTavares** [comment]
Working perfectly! Thanks!!
