### ISSUE TITLE
Create Explore Screen (populated with existing components)

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy-basics#4]
https://docs.google.com/document/d/1XH0LhgFuor4dfc0gfF96Ao-qk7771vRLn53jQplDe0I/edit#heading=h.53jt3te8wd42

**Comment by zepumph** [comment]
We will create side issues to tackle any new components that don't already exist in Buoyancy.

**Comment by zepumph** [comment]
- [x] From https://github.com/phetsims/buoyancy/issues/126#issuecomment-2050337096, percent submerged panel should default to closed.

**Comment by zepumph** [comment]
Working on this now.

**Comment by zepumph** [comment]
- [x] Test will all fluid radio buttons visible in studio

**Comment by zepumph** [comment]
Still TODO (perhaps in side issues?):

- [x] Density number line component (top center) https://github.com/phetsims/buoyancy-basics/issues/6
- [x] Should scale height sliders default to the ground @DianaTavares? Everywhere including the lab screen? AV edit: Spoke to DL and we decided to keep the height slider on the pools surface for better measurements.

**Comment by AgustinVallejo** [comment]
Adding TODOs from the remainders of the design doc:

- [x] custom masses range that goes from 0-27 kg, except if the custom density will exceed 15kg/L.
- [x] Delete Mystery Y since it has a >15kg/L density
- [x] Default: Both blocks Volume = 5.00 L, wood mass = 2.00 Kg, aluminium mass = 13.50 kg.

**Comment by AgustinVallejo** [comment]
@DianaTavares I think all the Explore Screen features are implemented now, minus the Density Readout Line https://github.com/phetsims/buoyancy-basics/issues/6. Let me know how it looks :)

**Comment by DianaTavares** [comment]
It is amazing!! 

From the design perspective, the lab screen has everything that was asked. KI will work on the new design of the density readout in the issue #6.

I will leave you to close this issue because I see that there are checkboxes unmark.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
