### ISSUE TITLE
Compare Screen: Depth lines should change color as density changes

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy-basics#8]
From https://github.com/phetsims/buoyancy-basics/issues/5#issuecomment-2096690650:

> * Also, the color of depth lines is not changing to white when the block's material gets dark:
> 
> ![image](https://private-user-images.githubusercontent.com/26031501/328285152-f2873cc4-7cbf-4bce-84e7-323e061a0f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMzcxOTMsIm5iZiI6MTcxNTAzNjg5MywicGF0aCI6Ii8yNjAzMTUwMS8zMjgyODUxNTItZjI4NzNjYzQtN2NiZi00YmNlLTg0ZTctMzIzZTA2MWEwZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDIzMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMjVlNjI4MTM1ODc1YmM1Y2ViYjZjZmQxZTAzZDRlMTYwYTBmZmVjZWYxNzAxMDA4YTU3OTQzMjUxMjQ2ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJMDUrl7JccjEBTRgAkirz2JG9Fqtib9TIoIBZEQXRI)

**Comment by samreid** [comment]
I'm confused about this issue, since I see the depth lines change color when changing the density of a custom material:

<img width="1244" alt="image" src="https://github.com/phetsims/buoyancy-basics/assets/679486/82d9ab99-1be0-4a3f-a375-94a87f8c7bac">

<img width="1402" alt="image" src="https://github.com/phetsims/buoyancy-basics/assets/679486/80edb06d-9339-4233-a0d8-2ab4a746a7b1">

The supporting code was committed in https://github.com/phetsims/density-buoyancy-common/commit/12db36882efb7521833ee9ab173c2219fba01400. What remains to be done for this issue?

**Comment by zepumph** [comment]
Here is where we are creating colors of materials for the compare screen,

https://github.com/phetsims/density-buoyancy-common/blob/552498deb280f47bd6b59a568936a381b706cc1c/js/common/model/CompareBlockSetModel.ts#L249-L254

**Comment by AgustinVallejo** [comment]
Added the same logic of the custom block, please review @DianaTavares

**Comment by DianaTavares** [comment]
I love that now the lines change with the density! But I think it does a little late. Currently, the change to white is in density 1.17 kg/L
![image](https://github.com/phetsims/buoyancy-basics/assets/26031501/99c6051f-79af-48b4-8ffb-7b07b650092a)



Look, these blocks have a density of 0.35 kg/L and I think that iut should be the moment to change! I edited the picture to change the lines to white and they have better contrast. 

![image](https://github.com/phetsims/buoyancy-basics/assets/26031501/ad58d27b-34fb-4ec4-9600-c4176f8b07b5)

**Comment by AgustinVallejo** [comment]
Please review the new threhold

**Comment by DianaTavares** [comment]
Amazing!!

**Comment by zepumph** [comment]
Just noting here that this threshold changes for all screens. I looked at the lab screen and the contrast looks really good.
